# Generated by Django 5.2 on 2025-04-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecheckoutsession",
            name="session_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stripecheckoutsession",
            name="session_expire_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stripecheckoutsession",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_checkout_sessions",
                to="payment_integration.plan",
            ),
        ),
    ]
