# Generated by Django 5.2 on 2025-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment_integration",
            "0002_stripecheckoutsession_session_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecheckoutsession",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
