# Generated by Django 5.2 on 2025-04-30 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_integration", "0003_stripecheckoutsession_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecheckoutsession",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Created"),
                    ("expired", "Expired"),
                    ("completed", "Completed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_subscriptions",
                to="payment_integration.plan",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="user",
            field=models.OneToOneField(
                help_text="a user should have only one subscription",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
