# Generated by Django 5.2 on 2025-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_integration", "0004_alter_stripecheckoutsession_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecheckoutsession",
            name="stripe_customer_id",
            field=models.CharField(max_length=255),
        ),
    ]
