# Generated by Django 5.2 on 2025-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment_integration",
            "0006_price_product_remove_stripecheckoutsession_plan_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_mode",
            field=models.CharField(
                choices=[("card", "Card")], default="card", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_type",
            field=models.CharField(
                choices=[("one_time", "One-Time"), ("subscription", "Subscription")],
                default="subscription",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Per product unit amount", max_digits=10
            ),
        ),
    ]
