# Generated by Django 5.2 on 2025-04-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_integration", "0007_price_is_active_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="invoice_url",
            field=models.CharField(blank=True, null=True),
        ),
    ]
