# Generated by Django 5.2 on 2025-05-01 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_integration", "0008_paymentrecord_invoice_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="user",
            field=models.ForeignKey(
                help_text="a user should have only one subscription",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
