# Generated by Django 5.2 on 2025-05-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_integration", "0009_alter_usersubscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="stripe_customer_id",
            field=models.CharField(max_length=100),
        ),
    ]
